### PR TITLE
Epg association (Recordings)

### PR DESCRIPTION
**Pull request by metaron-uk**
Two commits to fix EPG associations for Timers and add EPG associations for Recordings
1) Timers now show an icon for everything that will will be recorded in the EPG view
screenshot023
2) Recordings now show a 'play' icon and 'Play Recording' menu option in the EPG view
screenshot022

### CODE REVIEW

**Comment by janbar** [comment]
Please read my comments for commit 2a10a4f.
The other commit should be discarded because it breaks the spec: You could try to record a live-stream (pressing button record during live). This action ask the backend to keep the livetv recording. Internally it creates a rule for the program. You could examine the generated row of record table to understand what i mean.

**Comment by janbar** [comment]
You could try it also using mythweb:  By scheduling "Record only this showing" from the TV guide page. It will create a record relates epg program.

**Comment by janbar** [comment]
@metaron-uk timers already show an icon for everything that will be recorded. See below:
capture d ecran 2015-08-29 a 18 28 58
capture d ecran 2015-08-29 a 18 22 44
Do you have tested the latest with api 3.0.0 ?

**Comment by metaron-uk** [comment]
OK this removes the contentious 'upcoming' change. You are right it seems to work reasonably well at present, although I would expect 'Mot de passe' should have two 'multiple' icons, not one 'single' icon and one 'multiple' icon. In any case it can't be merged until 'edit rule' is possible without an EPG entry ...
I haven't used the 'keep what you are watching' record button option, but will investigate it. I know this is a case you were worried about before.

PS: There seems to be a bug in Kodi core which stops the 'play' icons appearing for recently recorded programs sometimes. I haven't worked out 100% what causes this yet, but it seems to work after a new recording was started since kodi restart.

**Comment by janbar** [comment]
About icons, these stuff are related to kodi. Now i think to get time to make a PR about icons because i would like to have colored icons regarding the state of the timer: Aborted, disabled, conflict ... If you have any suggestion then let me know please.

**Comment by metaron-uk** [comment]
About Icons, I think it would be good to have another icon for 'Conflict - not OK' status. (Maybe a red warning triangle with ! in it) to highlight conflicts.

I don't think Aborted/Disabled/Inactive status needs an icon. IMO this would just add 'clutter' to the EPG view. Maybe an icon for 'partially recorded' ('aborted'?), but maybe again this is just clutter. If a program didn't record properly, just don't show the 'play' icon.
I'd also suggest raising this on the forum before you PR - I'm sure other users / pvr maintainers will have strong opinions on the subject.

**Comment by metaron-uk** [comment]
@janbar - can you also bump the version of the addon in doityourself.
The 'kodi default' is now 3.2.2 to show it needs API3.0.0, but doityourself still shows as 3.2.1 even though it now requires API 3.0.0.

**Comment by metaron-uk** [comment]
Looks like the issue with 'play' icons not working properly might be something to do with CPU load while the recording is in progress. Makes sense as it seems to work OK on my Core2 with latest master, but not that well on RPi with the 24/8/15 millhouse build... 
See comments associated to https://github.com/xbmc/xbmc/pull/7905

**Comment by janbar** [comment]
For instance disabled timers or timers in conflict show an icon like they will record. Do you think it add clutter to show them with a different color ? The short fix will be not show them.

**Comment by janbar** [comment]
Thank Andrew. It is better again now ;)

**Comment by metaron-uk** [comment]
I'd suggest disabled timers should simply not show an icon. Someone disabled them on purpose. The same goes for recordings with a don't record over-ride.

For conflict not-ok imo it is misleading to show a timer icon (as it won't record).
No icon is correct, but not very helpful (the recording was not disabled on purpose)
A different (**warning**) icon would be much better. +1 for this.

**Pull request merged**
