### PR TITLE
Introduce UpdateFromTimer function

### PR DESCRIPTION
**Pull request by metaron-uk**
@janbar This introduces only the new function as you requested.
Now it will only modify settings allowed by MythScheduleManager::UpdateRecordingRule

The code can also change other settings (selected channel, 'any channel', 'any time', search type, rule type etc...), but other parts of code need fixing first (see Part 1 and Part 2 of my proposed changes).
You will get extra debug statements showing you what would have changed.

If you like this, I will prepare these fixes/changes, one commit for each setting I enable.

To really work properly I also need to do parts 1, 2, 6 and part of 4 (without the API 3.0.0 change). (see http://forum.kodi.tv/showthread.php?tid=230145&pid=2074228#pid2074228 )

### CODE REVIEW

**Comment by janbar** [comment]
So, i think we have to review becoming from existing code in "NewFromTimer". It seems for me to be a best approach copying existing code from NewFromTimer, adding as header necessary to retrieve the original rule, and then only set rule fields can be updated, keeping the same switch ordering. Also all timer type have a rule, even upcoming, override etc. And we need to retrieve the rule for them too.
Currently the PR seems to not support overrides, or i didn't see the subtlety.

**Comment by metaron-uk** [comment]
Thanks for taking the time to comment. I have some changes to make and some things to investigate further (handling of over-rides etc...). I will ping you when I have pushed a new version.

**Comment by janbar** [comment]
to retrieve rule and then duplicate it, we have to do something like that:

```
  MythRecordingRule rule;
  MythRecordingRuleNodePtr node;
  MythScheduledPtr recording = FindUpComingByIndex(entry.entryIndex);
  if (recording)
    node = m_manager->FindRuleById(recording->RecordID());
  else
    node = m_manager->FindRuleById(entry.entryIndex);
  if (node)
    rule = node->GetRule().DuplicateRecordingRule();
```

Here i never check or reference the parent ID because mythweb doesn't set it correctly. Else we could use switch on timerType to choose which branch : FindUpcoming or FindRule.

**Comment by janbar** [comment]
You could try by copying NewFromTimer, add necessary to retrieve the rule and then keep "rule.Set...()" you want. Is it a good way for you ?

**Comment by metaron-uk** [comment]
Probably it is best to use a switch on timer type. An upcoming will always have a parent rule, but a rule will not always have an upcoming, so we can't use the same method for both.
I noticed mythweb doesn't set parent ID correctly for over-rides as well. Makes it difficult to delete them when the parent is deleted....

We need to remember that UpdateRecordingRule uses 'create/delete over-ride' methods to deal with changes to upcoming, so spending effort here to get the parent rule may be wasted (I think this is why the current code appears to work). I will investigate.

**Comment by metaron-uk** [comment]
@janbar I've been through your comments and re-based:
1. 'FixRule' moved to MythScheduleHelper and made a separate commit
2. No update of rule type or search type (keep this for a separate PR later if necessary)

Some things to note:
- The order of 'case' statements is 100% the same as in NewFromTimer.
- The code for Upcoming/UpcomingManual/Override/Don't Record/Zombie etc... in UpdateFromTimer is the same as in NewFromTimer. MythScheduleManager::UpdateRecordingRule deals with updating these types, so only a minimal 'template' rule is required in UpdateFromTimer.
  If you want me to move the appropriate Upcoming/UpcomingManual/Override/Don't Record/Zombie code to UpdateFromTimer, I think it should be at least a separate commit. Do you want me to try this as part of this PR?
- It is not possible to actually change several of the settings as UpdateRecordingRule does not allow this yet (StartTime&EndTime / Filter / Channel/Callsign). Before I enable these, some 'fixes' in other parts of the code are necessary. Probably it is best I work on a separate PR for these once this PR is acceptable/merged. What do you think?

**Comment by janbar** [comment]
Yes you are right current code already use old rule to deal with the update: in MythScheduleManager::UpdateRecordingRule for the nodes, and MythScheduleManager::UpdateRecording for the leaf, I already retrieved the node and made the update duplicating the old rule. Here the code works correctly for all cases and specially for overrides.
So, now i wonder what is the benefit of this change. The job of "NewFromTimer" is to map timer entry with a rule, and never to do the "update" job: It must to be the opposite of "FillTimerEntry". These methods are only made to ensure the interoperability between timerEntry and rule.
Could you explain how this new method could help ?

**Comment by janbar** [comment]
Thanks for the new push. it will help me to understand what change comparing with NewFromTimer.

**Comment by metaron-uk** [comment]
Could you explain how this new method could help ?

Kodi can now edit parts of a field, without affecting others (e.g. set/reset 'FM_ThisChannel' without affecting 'FM_ThisSeries', FM_ThisEpisode or 'FM_ThisTimeAndDate')

**Comment by metaron-uk** [comment]
@janbar: This change by itself seems to have little point as you say. I don't see how I will convince you like this. It only makes sense with these other changes:
1. Allow the user to over-ride EPG information using _all_ settings displayed on the timer settings dialog (What you see is what you get).
2. Only use EPG information to set default information for a timer, not to update it or over-ride the timer settings dialog.
3. Remove the 'EPG search string' field from All/Once/Daily/Weekly timer types. I think this makes them too complex and the user won't know which field is controlling the timer.
4. Adjust Daily/Weekly timers to use FM_ThisDay / FM_ThisDayAndTime with RT_AllRecord and ST_NoSearch with >=0.27. Probably ST_FindWeekly/DailyRecord will do the same on 0.26. 
   ST_TitleSearch with RT_Daily/WeeklyRecord works well to record 'Any Time' for Daily/Weekly rules.
5. Merge RT_AllRecord / ST_TitleSearch with SEARCH_KEYWORD type.

I am now convinced that your MythTimerType / PVRtoTimerEntry method works well, but these ideas will need changes to several parts of MythScheduleManager, MythScheduleHelper and pvrclientmythtv.cpp (which I have prototyped) to work. I want to re-write and test my prototype code, incorporating your advice.

Although this is a different philosophy from the one pvr.mythtv currently implements, I think it is easier for users to understand and will work better with 'alternative' frontends.
_BUT..._
It is your addon and therefore I have to convince you first. I don't want to waste my life writing code you will never use. I may as well just complete my working prototype, install it on my frontends and move on.

How do you suggest I try to convince you it is worth trying to PR this idea of mine?

**Comment by janbar** [comment]
Seems your wishes concern essentially updating rule. The impacted code touch not only rules but other parts which handle upcoming management. I mean here about overrides (modifier rules). Currently involving "NewFromTimer" in update workflow is superflous: i can fill fields directly from the updated timer entry. The primary reason to have involve "NewFromTimer" was to check validity of updated entry: insure we can provide a valid rule from the updated entry else it returns the type RT_Unknown and the code fails. Also this check is not really needed to manage upcoming and i think to remove this call for them and then the impact could be limited. I let you know during the week.

**Comment by metaron-uk** [comment]
Makes sense. Let me know if there is anything I can do to assist.

**Comment by janbar** [comment]
So for now the API is full bug since changes from 2.1.0. Updating padding time move start time etc... Brief nothing is really testable. I will waiting beta1 for stable API and then IMO we have to fix API first before make any changes.

**Comment by janbar** [comment]
I tried to build your branch api3.0.0, but it cannot compile on windows: Probably missing some commits from my repo and you have introduced usage of primitive only available for posix system. Finally your timers timeslot are broken using GMT timezone: that could work in GB, unfortunately not here ;).
Hope it helps.

**Comment by metaron-uk** [comment]
@janbar: You say 'I will waiting beta1 for stable API and then IMO we have to fix API first before make any changes.' 
This worries me. If there are API bugs we can't wait for a stable API to fix them. We must do it now.
Q1) What is wrong with the API?

My pvr.mythtv api3.0.0 branch is a 'hack' and definitely missing the latest commits from your repo. I can't compile for windows, so don't know if I have introduced primitives only present on posix systems. I did not do this deliberately.
Q2) Can you send me the error log from your compiler?

You say "your timers timeslot are broken using GMT timezone".
Q3) Can you tell me which part of the code you think is 'broken'. This I can investigate and fix.

I will re-implement my api3.0.0 branch on your latest 'doityourself' code to get your 'thread safety' fixes :) I will also try and fix any bugs.

**Comment by janbar** [comment]
Q1: This change was not in API but in addon itself. Since timer timeslot is filled with time of next or last recorded that breaks rules using timeslot because these include padding. I fixed this change few hours ago. Since few weeks ago i consumed my time to fix bugs was not introduced with API 2.0.0, but caused by changes of behaviors of API which are not bumped. Really we have wasted our time coding on non stable base and my time as anyone is counted.

**Comment by janbar** [comment]
Q2: Seems your clone is based on commit which requires others to work with windows. You should rebase at least until next addon bump after the commit. The issue is in atomic.h.
Q3: MSVC doesn't have primitive gmtime_r which is only posix compliant (same for localtime_r : if you have a look in the addon sources you will see this function is inlined from tools.h). Finally this change cannot work. I don't know the motivation of this change.
Until now, i wonder how you could test and validate some change. Me i can't: Each time i try a scenario i find a bug bigger than my head :D. But this is part of the game.

**Comment by janbar** [comment]
@metaron-uk You shouldn't waste your time too. The API3 seems to be the best until now and finally guys agree now to wait reviewing before force a pull in the repo (remember of story about list array size...). Thanks for that.

**Comment by metaron-uk** [comment]
I didn't know gmtime_r was only on posix systems - that I can sort.
I found a bug in my kodi API 3.0.0 PR (broke during rebase). I'm fixing this and incorporating some comments from xhaggi. Then I'll take another look at this PR.
I know what you mean about using unstable code / API - I just tried re-basing on kodi master and it wouldn't even even configure :-(.

**Comment by metaron-uk** [comment]
This branch is a non-starter. Now API 3.0.0 is merged, I have greater freedom. Will re-implement these ideas and PR them separately.

**Pull request closed without merging**
