### PR TITLE
Show status & time of upcoming in parent rule

### PR DESCRIPTION
**Pull request by metaron-uk**
Adds support for:
Currently recording in upcoming list
Time of currently in progress recordings
Conflitcts in upcoming list

NB: While testing noticed that the 'Active' status for a conflict is the reverse of what it should be.
Currently shows as 'Active' when status is RS:Conflict, so creates a 'Don't Record' over-ride.
Should show as 'Inactive' so client creates a standard over-ride.

### CODE REVIEW

**Comment by metaron-uk** [comment]
Any chance you could exclude *.swp using the .gitignore file?
I keep checking in vi swap binaries (doh!)
Thanks.

**Comment by janbar** [comment]
Only for single record we show upcoming status. For repeating rule the status should be filled with rule state (Active/Inactive), same as value displayed in timer update screen.
Kodi show upcoming status in main screen, or you can disable grouping to show all in one page: 
capture_2015-07-03 17 06 28

**Comment by janbar** [comment]
About gitignore, no problem to add *.swp in development branch (doityourself). Now kodi feature is merged and soon i will merge the branch.

**Comment by metaron-uk** [comment]
@janbar - I've added an extra commit removing the 'status echo' feature. Let me know if this works for you / if you want them squashed + rebased on 'doityourself'.

**Comment by metaron-uk** [comment]
I agree with you. This PR is not ready yet.
There are other problems in this part of the code which break setting a specific time for a daily/weekly rules if a previous recording for that rule happened at a different time (e.g. you recorded the 6pm news before, but now want only the 10pm news).

**Comment by janbar** [comment]
Sorry it has been closed because i removed the related branch. I pause the dev for few days waiting ksooo's feature become more stable.

**Pull request closed without merging**
