### PR TITLE
Limit channel tuning attempts

### PR DESCRIPTION
**Pull request by janbar**
It replaces PR #10

### CODE REVIEW

**Comment by janbar** [comment]
So i format fixes as needed and rebase with 3 commits. Also the default value for the new setting will be TRUE, so limiting channel tunning attempts.
@MikeB2013 , is it ok for you ?

**Comment by janbar** [comment]
I close the original PR which is now deprecated.

**Comment by MikeB2013** [comment]
@janbar,

Thanks for your work on this.  I now understand what is required.

Default of TRUE is ok with me. 

Mike

**Comment by janbar** [comment]
I think add a new tab in setting screen to separate advanced UI settings. For sample "manage icons" items or EDL behavior could be grouped in special tab. It could be more readable. Isn't it ?
Also if you see gramatical erroneous, tell me please before i merge it. Remember you are authored of these commits !

**Comment by MikeB2013** [comment]
@janbar 

I am happy with the wording!

Unless you are thinking of adding many more items in the future to the Advanced tab, it is probably not worth adding/splitting out to an advanced UI settings tab. I think the defaults are good for most people, so it is a minority that would even go to Advanced tab. 

Mike

**Pull request merged**
