### PR TITLE
Init launcher

### PR DESCRIPTION
**Pull request by janbar**

### CODE REVIEW

**Comment by janbar** [comment]
@teeedubb , now it try forever. I can't merge this PR for now because kodi crashes in pvr manager: There is a bug in CPVRTimerType causing segfault.

**Comment by janbar** [comment]
@ksooo, please could you check this point:

    Thread 1 (Thread 0x7fe53385d700 (LWP 30577)):
    #0  strlen () at ../sysdeps/x86_64/strlen.S:106
    #1  0x0000000001186e02 in PVR::CPVRTimerType::InitMaxRecordingsValues(PVR_TIMER_TYPE const&) ()
    #2  0x0000000001188491 in PVR::CPVRTimerType::CPVRTimerType(PVR_TIMER_TYPE const&, int) ()
    #3  0x0000000000fc9b73 in PVR::CPVRClient::GetAddonProperties() ()
    #4  0x0000000000fca160 in PVR::CPVRClient::Create(int) ()
    #5  0x00000000011eb6b7 in PVR::CPVRClients::UpdateAddons() ()
    #6  0x00000000011fb5c2 in PVR::CPVRStartupJob::DoWork() ()
    #7  0x0000000000c78e49 in CJobWorker::Process() ()
    #8  0x0000000000d0cd95 in CThread::Action() ()
    #9  0x0000000000d0cfef in CThread::staticThread(void*) ()
    #10 0x00007fe5529336ba in start_thread (arg=0x7fe53385d700) at pthread_create.c:333
    #11 0x00007fe54b38f82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

**Comment by janbar** [comment]
Seems the PVRTimerTypes array isn t initialized with zero before passing its pointer to the addon. I don t remember if that is the current practice with xbmc. As workaround I will reset with 0 for each new entry before returning.
@ksooo, please let me know what is the practice to apply with pvr structs.

**Comment by ksooo** [comment]
> @ksooo, please let me know what is the practice to apply with pvr structs.

 Yep, it is. You need to memset zero every types array member you are actually filling, no need to zero the rest as this is handled via the size GetTimerTypes returns .

Example: https://github.com/kodi-pvr/pvr.hts/blob/master/src/Tvheadend.cpp#L615

**Comment by janbar** [comment]
Thanks @ksooo

**Comment by teeedubb** [comment]
Thanks @janbar and @ksooo. Your work is much appreciated. 
Tested with the following two scenarios and is working well - backend starting after kodi has started at boot up and backend suspends and is restarted while kodi is running.

**Pull request merged**
