### PR TITLE
Added minimalistic support for PVR Addon API 5.3.0

### PR DESCRIPTION
**Pull request by ksooo**
Related kodi PR: https://github.com/xbmc/xbmc/pull/12303

### CODE REVIEW

**Comment by ksooo** [comment]
@janbar Please check whether PVR_TIMER_TYPE_SUPPORTS_ANY_CHANNEL should be added to any of the timer types you have defined and open a follow-up PR in case. Otherwise "Any channel" will no longer be available in the timer settings' dialog channel list.

**Comment by janbar** [comment]
Thanks. I will check to update timers requiring the corresponding flag.

**Comment by janbar** [comment]
Can I merge it now, or you suspect a NO GO for the upstream PR ?
Edit: I think you should have permission to merge it, since I added you as collaborator.

**Comment by ksooo** [comment]
> Can I merge it now, or you suspect a NO GO for the upstream PR ?

 Please wait until tomorrow. I don't expect a nogo, but today's nightly build will contain broken pvr.mythtv if you merge now.

 Thanks for giving me push access to your repo, btw. So, is it okay if I merge this PR right after the related kodi PR got merged?

**Comment by janbar** [comment]
Yes sure it is okay.

**Comment by janbar** [comment]
Also if any future change is required to make it work for the nightly build you could now merge your PR.

**Comment by ksooo** [comment]
Okay, thanks.

**Pull request merged**
