### PR TITLE
Update MythChannel.cpp

### PR DESCRIPTION
**Pull request by rosenhauer**
Check for keyword to move channel to "Radio" group in the channel's callsign 
If "-[RADIO]" is found then return true else return false

### CODE REVIEW

**Comment by janbar** [comment]
Thanks.

**Comment by janbar** [comment]
I merged the PR with the master branch. The next nightly build of Kodi 18.0 will include this change.

**Comment by rosenhauer** [comment]
I just tested it with the nightly and and it works as expected.  If there any way to get builds of this in the 17-Krypton branch?  There hasn't been a nightly since 11/14/17.  I'm not ready to jump to Leia quite yet.

**Comment by janbar** [comment]
Depending of your target platform, you have to compile yourself for krypton. You could build it easily on linux or windows, using my branch devel-17.
Prior to install your new build, uninstall the old addon.

**Comment by rosenhauer** [comment]
Thanks.  I've built it on Linux but need Android and haven't been able to get it to build.  But that's a project for another day.  I was just hoping that maybe there was a build system that was generating Krypton builds still.

**Pull request merged**
