### PR TITLE
Add configuration to allow EPG/Timers to be disabled.

### PR DESCRIPTION
**Pull request by lucylang**
With the growing number of cheap, low-memory, low-power Android
devices, it means one user can have several Kodi devices. Most of
these will never be used for scheduling so allow it to be optionally
disabled.

This is also useful for people that only use mythweb/mythfrontend
for scheduling or use Kodi occasionally.

You can still access live tv even with EPG and timers disabled
such as via the channels menu item.

The new options are in the advanced settings "enable EPG" and
"enable timers". Both require a restart of Kodi to take effect.

By default, most skins will still show the EPG and timers menu
items even if they are disabled.

After disabling the EPG, the EPG menu item will still contain data
until it is expired.

### CODE REVIEW

**Comment by janbar** [comment]
Thanks,
Also these new switches can be moved at the end of the first tab of settings instead in advanced tab.
Finnally you should remove "requires restart" , cause kodi will popup this info on save.

**Comment by lucylang** [comment]
Thanks, I hadn't noticed the ADDON_STATUS_NEED_RESTART. I've moved the settings to the first tab, updated the language text to remove "needs restart" and return the correct status.

**Comment by janbar** [comment]
Testing nightly build of kodi, it crash by going to the timer screen. The issue is caused by dereferencing null pointer of timerType. I will have a look to fix it in kodi later.
For epg it's weird, because we have no info about the current shows. I think we could at least keep the capability to true and then only retrieve 4 hours from the guide, which is large enough to see what happen for the moment.

**Comment by lucylang** [comment]
For EPG there is an option in LiveTV->Guide->Hide No Information Available Labels which makes it look slightly less weird since Kodi then fills the guide with "No information available."

In  the Titan skin you can delete menu items you don't want so the EPG and timers items can vanish.

Sorry about the crash.

I've compiled nightly and it crashes if I try to add a timer. Looks like the dialog logic assumes m_typeEntries will be >0 in a lot of places. I patched a couple of cases locally but it failed elsewhere. Maybe we are the only pvr that sets timers=false.

I've done more investigating and it seems pvrclient-mythtv also has subscriptions via the mythprotocol so listens to all backend messages including SCHEDULE_CHANGE messages which then causes the m_scheduleManager to re-request and cache all timers. Kodi correctly doesn't request the timers if supports timers=false.

I'll need to disable the m_scheduleManager and I'll have to investigate the callback logic more tomorrow to see what interactions there are especially on re-connect.

Even if the crash is fixed then it might require more work to let the user know they can't create timers, so ends up more work than the benefit?

I can drop the timer changes and just leave the EPG  changes. Or if you think GUI looks too confusing then I'm also happy to abort the patch. Keeping 4 hours of EPG would require a change in Kodi since the lowest value is one day and that's also an alternative.

**Comment by janbar** [comment]
It is very easy to disable schedule manager. Just dont instantiate it and dont subscribe to message. I will show you once i am at home.

**Comment by janbar** [comment]
To disable schedule manager, you have to by pass lines: https://github.com/janbar/pvr.mythtv/blob/doityourself/src/pvrclient-mythtv.cpp#L148 to https://github.com/janbar/pvr.mythtv/blob/doityourself/src/pvrclient-mythtv.cpp#L152

To avoid crash from kodi, we can keep "timer" feature enabled but don't start the manager. Also i had already managed the issue because in all way i fill one entry in timerEntry array.
About epg we could limit request range to 4 hours: same thing, it is easy to resolve in the dedicated function GetEpgForChannel(). There if period is out then just return, else we have to truncate the range to 4 hours.

**Pull request closed without merging**
