### PR TITLE
no confirmation dialog on startup

### PR DESCRIPTION
**Pull request by 5im-0n**
do not ask the user if he wants to retry connecting to the backend if
the backend does not respond.

### CODE REVIEW

**Comment by janbar** [comment]
We have to use a dedicated thread to do this job. I created the PR #65 to override this one.
I added a launcher which try to connect for 15 minutes, and every 30 seconds. Passed the delay the launcher stop.

**Comment by teeedubb** [comment]
Hi janbar,

Is it possible to have the launcher attempt to connect indefinitely? Sometimes I will wake the backend after using kodi for a long time (ie local music, internet streams or playing games). Not setting a hard timeout would mimic the behaviour of the addon in previous versions of kodi.

Thanks for your time.

**Comment by 5im-0n** [comment]
@janbar you are awesome

**Comment by janbar** [comment]
@teeedubb , yes it is. But to be clean, I have to stop error log of CPPMyth to avoid filling of log with connection error. I will add a commit for that.

**Pull request closed without merging**
