### PR TITLE
Tidyup in preparation for API3.0.0 changes

### PR DESCRIPTION
**Pull request by metaron-uk**
Re-formats the MythTimerEntry defaults, so adding extra fields (if necessary in future) will be less likely to cause merge conflicts.

Other change removed as supply_subtitle_as_confluence does what I wanted to propose

### CODE REVIEW

**Comment by janbar** [comment]
I checked the PR for API3 an i didn't see any new field subtitle in timer tag. The MythTimerEntry has already a field subtitle in its struct epgInfo. So i don't know the motivation to add this field.

**Comment by janbar** [comment]
Please have a look on my branch "supply_subtitle_as_confluence". It will show you IMO what to do.
I know you are not yet aware how to propose changes and the followings explain a general guideline for some points i see here:
- Don't change place of line of code when only updated (https://github.com/metaron-uk/pvr.mythtv/commit/8603a23c00ec208e1ac16860605414df162ff6a7#diff-4a96ce340435e1efecda6f9744992356L534). It could be difficult to merge with other branch.
- Don't change format, indentation etc if no code is updated and try as possible to preserve the format/style of authors as possible. These "cleanup only" should be done in separated commit because they don't relate any changes and often authors don't like these changes because they break the history of code. I know it could be not easy, I done same errors before, but we cannot violate the code from author, breaking history by changes which are not.
  Let me know your opinion. Also is the commit in the branch "supply_subtitle_as_confluence" does what you want to propose ?

**Comment by janbar** [comment]
Sorry I missed to explain what i done in "supply_subtitle_as_confluence". Please read the followings:
- No more subtitle in timerEntry because it isn't and will not used by timer tag. As input we have already the field epgInfo.subtitle which contains the right data: epg subtitle.
- Only title of upcoming has to be formated as recording (or epginfo). Title of rules is not related to this.

**Comment by metaron-uk** [comment]
@janbar - thank you for taking the time to explain the reasons to me. I promise to follow these rules more rigorously in future, so hopefully you won't need to re-write my code every time before a merge :-(.
Yes, supply_subtitle_as_confluence does exactly what I wanted to propose.

**Comment by janbar** [comment]
So you could replace the commit "Supply subtitle separate from title" with the updated version from  supply_subtitle_as_confluence and push again ?
I will test it and if all is okay i will merge this PR (including format Only too)

**Comment by metaron-uk** [comment]
OK pushed with your commit from supply_subtitle_as_confluence. I've tested the combination here and they seem to do what I expect. Thanks.

**Comment by janbar** [comment]
That's work. Rules keep their original title on update and upcoming use skin.confluence format as expected. Thanks.

**Pull request merged**
