### PR TITLE
Add 'Record new and expire old' support

### PR DESCRIPTION
**Pull request by metaron-uk**
Implemented for all timer types which support 'Lifetime'
Allows selection of 2, 7 and 14 recordings to keep
Other values shown as ? and not changed unless a selection is made

screenshot008

### CODE REVIEW

**Comment by metaron-uk** [comment]
Rebased on top of 30e89d9271cf0eb33572091c1a0d3a28d3a4b315 (30/7/2015) from series_recordings

**Comment by janbar** [comment]
Thanks metaron. Your idea is good.

**Comment by janbar** [comment]
the handling is complex and pvr client should never know what about: all business rules should be inside schedule manager. Client has to know id and select list to display. I will prepare a commit inspired from your idea. I let you know.

**Comment by metaron-uk** [comment]
Thanks!

I agree it's a good idea to keep the complexity inside MythScheduleManager, rather than pvr-client.
The problem I had here, which inspired my subsequent forum posting ( http://forum.kodi.tv/showthread.php?tid=230145&pid=2041898#pid2041898  ) was where to put the 'convert PVR_TIMER to MythRecordingRule' logic as there isn't a clear one-to-one mapping in this case.

I can see you intend MythTimerEntry class to act as the bridge between pvr-client and MythScheduleManager, but I'm not clear if you intend it to have variables matching PVR_TIMER variables, or MythRecordingRule variables, or something else. Why not just use one of the other classes?
I'd like to be developing patches which fit in with your 'intended separation' without you having to spend the time on re-work. You do deserve to get _some_ sleep!

Do you think you could summarize what you want to see put where and why (maybe on the forum in case someone else wants to contribute)?

**Comment by metaron-uk** [comment]
Just seen and tested your implementation. Works for me :-)
Makes sense to miss out 'Keep up to 1 recordings' as that's just a "record one" rule.

**Comment by janbar** [comment]
Do you think we have to keep 'autoexpire' off when 'maxepisodes' is set ? (I don't use this feature here, so i don't know what is needed)

**Comment by janbar** [comment]
What else, about PVR_TIMER: this stuff is really bad. Just use it to get input of user. Before i created a method in client to fill data into myth rule. But this solution didn't care about version of backend. So it is time to refactor it and trying to build something more flexible. Now i try to make MythTimerEntry the entity allowing exchange of data between client and scheduler. It contains understandable data from client like titile, starttime etc, and anonymous data which are version dependent and are understandable only by user and scheduler: duplicate method, priority, expiration: These things are not handleable by client (core of pvr.mythtv) and pvrmanager (kodi). So all business rules about should be implemented inside scheduleManager or scheduleVersionHelper.

**Comment by metaron-uk** [comment]
I checked with your maxepisodes code and 0·27.
Using 'Keep 2 recordings' I've now got two entries of 'World's most expensive rides' in the library and all future showings are listed as 'Too Many' and shown as 'Disabled' upcoming recordings.
Seems to work as you have it now, so keep it like that.

**Comment by metaron-uk** [comment]
Regarding PVR_TIMER / MythTimerEntry I can see the reason. The problem seems to be that MythTimerEntry doesn't know what 'PVR_TIMER_TYPE' it has, so you can't do clever things like changing the RecordingRule from a 'Channel' to an 'All' with confidence that you won't break something. I think it would be good to know before you change between 'Any Channel' and 'Channel Reocrd' on 0.26 (on 0.27 it's easy, just reset the filter). Maybe the solution is to add TimerType to MythTimerEntry?

I'm getting really frustrated at the moment as most of my rules are 'Any Channel, Record All' (Mythweb default) and every time I try to edit one in any way using kodi, it says get lost, I can't find a matching EPG entry! _Please_ can the dependency on EPG for editing a timer be removed?

**Pull request closed without merging**
