### PR TITLE
Set iLastPlayedPosition in GetRecordings()

### PR DESCRIPTION
**Pull request by b-pass**
Small TODO in the code, Seems simple enough....

### CODE REVIEW

**Comment by janbar** [comment]
So I think we have to remove TODO and add a comment for the good reason we don t fill it at this stage.

**Comment by b-pass** [comment]
If you don't fill it at this point then Kodi won't show the recording as partially watched in the GUI.

**Comment by janbar** [comment]
Yes I agree. But in state of art this kodi's feature can't be resolved with the backend call "GetSavedBookmark". The Myth backend store bookmark using a recording mark. Retrieving the time position of a mark need to match the frame number with its time position. It requires lot of resource from the backend. The addon function GetRecordings() is called every time a recording is updated i.e its duration change (near every second during recording). That's the reason why this function only transfer cached recordings data to PVR array structure.
Instead we could imagine to load this information elsewhere. But I could imagine user having thousand recordings seeing its backend overloaded.
Else we have the programInfo's field "programFlags" which could contains this kind of data, not the time position but a boolean ... I have to check that.

btw, I start thinking you have a hardy hardware to host your backend and a strong gigabytes network ;-)

**Comment by janbar** [comment]
here https://code.mythtv.org/doxygen/programtypes_8h_source.html#l00121 , seems value 0x00000010 means recording has a bookmark.
Now the next question is : Can we fill value 1 in the field and be sure PVR will call always "GetLastPlayedPosition()" to retrieve the right value ?

**Comment by janbar** [comment]
I have already implemented the function which save the feature `MythProgramInfo::HasBookmark()`. Great.
Still trying to place 1 when recording has a bookmark. And checking kodi continue to retrieve the right value using standard pvr call GetLastPlayedPosition.

**Comment by b-pass** [comment]
You're right, janbar.  Even about the gigabit ethernet... but mostly about `HasBookmark()`.

Setting to iLastPlayedPosition to 1 allows the Icon to show in Kodi, but Kodi still calls `GetRecordingLastPlayedPosition()` and uses that value when the user starts watching a recording.

I've checked in that change and squashed it.

**Pull request merged**
