### PR TITLE
Add subtitle/season/episode to Timer display (single shot types)

### PR DESCRIPTION
**Pull request by metaron-uk**
This PR adds 'Subtitle' to the end of single shot timers (Manual/This/One) where it exists in the rule.
A fix for cppmyth is included as a separate commit (SubTitle not Subtitle)
Where data for Season/Episode is also available, this is also added.
The format for Season/Episode display is changed to match Kodi default for 'Specials'
(Season/Episode display not tested here as my 0.27 backend doesn't provide it for timers)

screenshot024

ping @janbar

### CODE REVIEW

**Comment by janbar** [comment]
About rule title. Few time ago you ask me to allow update the value in timer update screen. I didn't enable it because there is an issue in kodi to display the updated title and without backend callback the title still unchanged. We have to find the proper solution to fix it before enabling update of the field. Now i haven't solution made in addon without impact (performance issue due to double callback). So only a PR for kodi could fix it. Currently i hadn't time to fix it in kodi and i was hoping this bug could be fixed by api changes. Today i haven't test it again with api 3.0.0.

**Comment by janbar** [comment]
Okay, so we keep the change for "S" on upcoming with episode only :+1:

**Comment by metaron-uk** [comment]
rebased with only the libcppmyth fix and upcoming season/episode changes.

**Comment by janbar** [comment]
Thanks Andrew. The fix for cppmyth has been merged in its repository.

**Comment by metaron-uk** [comment]
thanks :-)

**Pull request merged**
