### PR TITLE
Update PVR API 6.2.0

### PR DESCRIPTION
**Pull request by phunkyfish**
v6.2.7
- PVR API 6.2.0

### CODE REVIEW

**Comment by phunkyfish** [comment]
API changes merged in kodi, please merge this and create a release. Otherwise, the breaking change can effect your users who run kodi nightlies.

ios-armv7 error unrelated.

**Comment by janbar** [comment]
Thanks @phunkyfish

**Comment by phunkyfish** [comment]
Not for this field. It creates a CDateTime from the temporary char* so it should be ok.

**Comment by phunkyfish** [comment]
Correction, you are right. Apologies for the incorrect PR.

**Comment by janbar** [comment]
I fixed it with the latest tag (6.3.0-Matrix)

**Pull request merged**
