### PR TITLE
[Matrix] API change update

### PR DESCRIPTION
**Pull request by AlwinEsch**
Related to xbmc/xbmc#17586 and to bring in after them.

### CODE REVIEW

**Comment by janbar** [comment]
Oki. I will wait your GO to merge it. Sorry.

**Comment by janbar** [comment]
@AlwinEsch , is a GO to merge this PR ?

**Comment by AlwinEsch** [comment]
Still not, sorry. 
There are still discrepancies with other requests to Kodi https://github.com/xbmc/xbmc/pull/17633, which is also related to this one for here xbmc/xbmc#17586.

**Comment by AlwinEsch** [comment]
The request about API update on Kodi is in, this can then also brought in and released.

**Comment by MilhouseVH** [comment]
Looks like this has been merged into the wrong branch, should have gone into Matrix.

**Comment by janbar** [comment]
It is the right branch. I will merge it too in Matrix. My desktop for dev is in maintenance. Few minutes to go....

**Pull request merged**
